"""initial schema

Revision ID: c9e846a57614
Revises: 
Create Date: 2026-04-25 12:07:08.122120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e846a57614'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.Enum('arvo_osuustili', 'osakesaastotili', 'espp', name='accounttype'), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_treatment', sa.Enum('standard', 'deferred', 'espp', name='taxtreatment'), nullable=False),
    sa.Column('ost_lifetime_deposits', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('price', 'news', 'earnings', 'recommendation', 'rebalance', 'tax', name='alerttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'action', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('new', 'read', 'dismissed', name='alertstatus'), nullable=False),
    sa.Column('related_symbol', sa.String(length=20), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_type', sa.Enum('daily_summary', 'rebalance', 'tax_optimization', 'news_impact', 'strategy_review', name='analysistype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pair', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'date', name='uq_fx_rate_pair_date')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_market_price_symbol_date')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_allocation', sa.JSON(), nullable=False),
    sa.Column('risk_tolerance', sa.Enum('conservative', 'moderate', 'aggressive', name='risktolerance'), nullable=False),
    sa.Column('rebalance_threshold_pct', sa.Numeric(), nullable=False),
    sa.Column('tax_optimization_enabled', sa.Boolean(), nullable=False),
    sa.Column('custom_rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('instrument_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_quantity', sa.Numeric(), nullable=False),
    sa.Column('avg_cost_basis_eur', sa.Numeric(), nullable=False),
    sa.Column('total_cost_eur', sa.Numeric(), nullable=False),
    sa.Column('current_price_native', sa.Numeric(), nullable=True),
    sa.Column('current_price_eur', sa.Numeric(), nullable=True),
    sa.Column('current_value_eur', sa.Numeric(), nullable=True),
    sa.Column('unrealized_pnl_eur', sa.Numeric(), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.Numeric(), nullable=True),
    sa.Column('portfolio_weight_pct', sa.Numeric(), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('instrument_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_type', sa.Enum('buy', 'sell', 'dividend', 'espp_purchase', 'espp_sale', 'deposit', 'withdrawal', name='transactiontype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price_native', sa.Numeric(), nullable=False),
    sa.Column('price_eur', sa.Numeric(), nullable=False),
    sa.Column('total_native', sa.Numeric(), nullable=False),
    sa.Column('total_eur', sa.Numeric(), nullable=False),
    sa.Column('fx_rate', sa.Numeric(), nullable=True),
    sa.Column('fees', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('holdings')
    op.drop_table('strategies')
    op.drop_table('news_articles')
    op.drop_table('market_prices')
    op.drop_table('fx_rates')
    op.drop_table('analysis_history')
    op.drop_table('alerts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
